services:
  - type: web
    name: creatorOS
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_NAME
        value: CreatorOS
      - key: SESSION_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_APP_URL
        value: https://creatorOS.onrender.com
      - key: AZAMPAY_APP_NAME
        value: CreatorOS
      - key: AZAMPAY_CLIENT_ID
        sync: false
      - key: AZAMPAY_CLIENT_SECRET
        sync: false
      - key: AZAMPAY_API_URL
        value: https://sandbox.azampay.co.tz
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false